# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-2019

variables:
  buildConfiguration: 'Release'
  projectName: 'WebAppService'
  websiteName: 'WebApprService'
  appPoolName: 'WebAppService'

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: 
        steps:
        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk '
        - task: DotNetCoreCLI@1
          displayName: dotnet restore
          inputs:
            command: 'restore'
            projects: '*.sln' 
        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            command: 'build'
            projects: '''*.sln'''
            arguments: '--configuration Release'
        - task: DotNetCoreCLI@2
          displayName: test
          inputs:
            command: 'test'
            projects: '''*.sln'''
            arguments: '--configuration $(BuildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: 'publish the project'
          inputs:
            command: publish
            projects: '**/*.csproj'
            publishWebProjects: false
            arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
            zipAfterPublish: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'